### PR TITLE
Add carousel

### PR DESCRIPTION
**Pull request by chartgerink**
Did some searching for packages and two seemingly viable options came up:

1. [SwiperJ](https://swiperjs.com/react#styles)S
2. [react-carousel](https://brainhubeu.github.io/react-carousel/docs/gettingStarted)

This draft PR gives an example using `react-carousel`.

For either of them the designs will need only a bare minimum, because we will use other components inside of them (so we can show testimonials, videos, etc):

- [ ] Arrow left (active + inactive)
- [ ] Arrow right (active + inactive)
- [x] Slide indicator (active + inactive; optional - my preference to not have this initially for implementation speed)

As a result, I think this should be relatively easy to provide design instructions for using the Carbon icons.

### CODE REVIEW

**Comment by chartgerink** [comment]
This thing has become a headache for me. It seems like all carousel options have quirks!

This one renders and at least allows me to adjust the navigation a bit. However, I am not able to do 1:1 design implementation at the moment. Quirks abound! 

If I try, the closest I can get rn is:
Screenshot 2021-08-03 at 14 02 19

However, with this there is these issues:

1. Can't get the box 2.5rem and the icon 1.5rem, because they're styled through the same element
2. If I create a parent element, it doesn't show where you would expect it to?!
3. There are breakpoints in the library that really don't work nicely for this styling
4. outside the content width (can get them in there easily but honestly was )

If I remove this styling and take the default one, it looks as such:

Screenshot 2021-08-03 at 14 02 28

What we could do is replace it with autoplay, save us a lot of headache or take one of these options. Whatcha think @psobrakseaton? There's also the option still to add the dots at the bottom, I guess... See below for fiddling around.

https://user-images.githubusercontent.com/2946344/128015348-56907059-1ecf-42ff-80cb-588d777cc500.mov

**Comment by psobrakseaton** [comment]
I am much more inclined towards the dot indicators over the autoplay. Do touch gestures work with this as well?

**Comment by chartgerink** [comment]
Yeah touch gestures work - will remove autoplay. If you'd like, the dot can easily be replaced with another icon if you'd like.

**Comment by psobrakseaton** [comment]
Sounds good! I say we leave the indicators as they are. Can we use "primary" for the active dot and mono-300 for the inactive?

**Comment by chartgerink** [comment]
Ready for review @psobrakseaton - i think this works decently enough for our purposes and it is nice and minimal 😉

**Review by psobrakseaton — APPROVED** [review]
I like it! I think this is nice and minimal (as you said). I will do some more thinking on it as well in the coming days, but for now this is good.

**Comment by chartgerink** [comment]
Thanks @psobrakseaton! 

I moved the slider to the testimonials, but because there is only one at the moment you won't see it pop up. 😊

**Pull request merged**
