### PR TITLE
Add Callout component

### PR DESCRIPTION
**Pull request by chartgerink**
This PR adds a callout component. It is one component with the various elements across the variations abstracted out into various parameters. It is rather verbose and colors are not implemented by default, allowing for more flexibility upon implementations. 

The examples here contains the example designs, but we can pretty much mix and match custom ones at any time, switching out the icons, colors as we need.

### CODE REVIEW

**Review by psobrakseaton — CHANGES_REQUESTED** [review]
This is quite great! I think the only thing I would like to change is that for the "Details" and "Close" buttons, if we could have the interaction/hand mouse cursor appear that would be best.

**Review by psobrakseaton — APPROVED** [review]
Brilliant! Thank you!

**Comment by chartgerink** [comment]
- [ ] No left right margin on >960px

**Comment by chartgerink** [comment]
Updated the component to not have margins >1024px (breakpoint in tailwind) and removed the examples of the callouts. Code included below for reference 😊 

Screenshot 2021-08-03 at 10 47 21

```jsx
<Callout icon={<WarningAltFilled24 className="text-libscie-yellow-700" aria-hidden="true" />} 
  bg="bg-libscie-yellow-100"
  title='Attention needed'
  description={<>
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid pariatur, ipsum similique veniam quo
    totam eius aperiam dolorum. 
    </>}
/>
<Callout icon={<Misuse24 className="text-libscie-red-700" aria-hidden="true" />} 
  bg="bg-libscie-red-100"
  title='There were 2 errors with your submission'
  description={<ul className="list-inside list-disc">
    <li>
      Your password must be at least 8 characters
    </li>
    <li>Your password must include at least one pro wrestling finishing move</li>
    </ul>}
/>    
<Callout icon={<CheckmarkFilled24 className="text-libscie-green-700" aria-hidden="true" />} 
  bg="bg-libscie-green-100"
  title='There were 2 errors with your submission'
  description="Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid pariatur, ipsum similique veniam."
  actionsBottom={[
    {
      text: 'View status',
      link: 'https://google.com'
    },
    {
      text: 'Dismiss',
      link: 'https://google.com'
    }
  ]}
/>  
<Callout icon={<InformationFilled24 className="text-libscie-blue-700" aria-hidden="true" />} 
  bg="bg-libscie-blue-100"
  description="A new software update is available. See what’s new in version 2.0.4."
  actionRight={{
    text: 'Details',
    icon: <ArrowRight16 />,
    action: () => {window.open('https://google.com')}
  }}
/>   
<Callout icon={<WarningAltFilled24 className="text-libscie-yellow-700" aria-hidden="true" />} 
  bg="bg-libscie-yellow-100"
  description={<>
    You have no credits left. <a className="border-b-1 text-libscie-mono-900 border-libscie-mono-900 hover:bg-transparent hover:text-libscie-mono-900" href="https://google.com">Upgrade your account to add more credits</a>.
  </> }
  flag="border-libscie-yellow-700"
/>    
<Callout icon={<CheckmarkFilled24 className="text-libscie-green-700" aria-hidden="true" />} 
  bg="bg-libscie-green-100"
  description="Successfully uploaded"
  actionRight={{
    action: () => {alert('hi')},
    text: "Close",
    icon: <Close16 />
  }}
/> 
```

**Pull request merged**
